import 'package:flutter/material.dart';



bool educationalChatbot = false;
bool playlistChatbot = false;

List<String> playlistChatbotDefaultQuestions = [
  "How do my inputs match with this playlist?",
  "What was your reasoning behind picking these stocks?",
  "What's the average return of my playlist?",
  "If I want something a bit riskier for higher returns, which stocks would you substitute from this playlist?",
];

dynamic tailoredPlaylistGeneratedMap = {};
List<dynamic> tailoredPlaylistGeneratedStocks = [];


int currentOnboardingQuestion = 1;
int totalOnboardingQuestions = 7;

int currentPlaylistQuestion = 1;
int totalPlaylistQuestions = 16;

List<Map<String, dynamic>> questions = [
  {
    "question": "How familiar are you with trading & investing?",
    "options": [
      "Totally new. Haven’t bought a stock, don’t really know where to start.",
      "I get the basics — like stocks, ETFs, and risk — but haven’t really invested.",
      "Tried an app once. Maybe bought a stock or fund just to see what happens.",
      "I track the markets, follow finance content, and compare options before I invest.",
      "I manage my own trades and make confident investment calls."
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  },
  {
    "question": "How steady is your income right now?",
    "options": [
      "It’s unpredictable — changes month to month",
      "Somewhat steady — freelance, part-time, or in transition",
      "I have a regular salary, but it's just enough to cover my basics",
      "I have a consistent salary or stable business income that covers my needs",
      "I have extra income — from salary, business profits, or multiple sources"
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  },
  {
    "question": "What’s your investment goal right now?",
    "options": [
      "Just wanna keep my money safe",
      "Make a little passive income",
      "Grow my savings slowly & steadily",
      "Build serious long-term wealth",
      "Shoot for high returns — I'm all in"
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  },
  {
    "question": "What's your vibe when it comes to investment risk?",
    "options": [
      "I’d rather play it safe — I can’t afford to lose much.",
      "I’m cautious, but okay with taking small risks here and there.",
      "I’m cool with ups and downs if the long-term potential is solid.",
      "I’m comfortable with high risk — it’s how you get real results.",
      "I actively seek very high-risk for higher potential returns."
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  },
  {
    "question": "How long can you wait before needing your invested money back?",
    "options": [
      "Within 3 months",
      "3–12 months",
      "1–3 years",
      "3–5 years",
      "5+ years"
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  },
  {
    "question": "What kind of returns are you expecting per year?",
    "options": [
      "20–25% — I’m fine with bank-level returns, just keeping it stable",
      "25–35% — I want more than banks, but nothing too risky",
      "35–50% — I’m aiming for decent growth and can handle some ups and downs",
      "50–70% — I’m open to bold moves for higher returns",
      "70%-100% — I’m chasing very big gains and willing to take the heat"
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  },
  {
    "question": "How much of a loss can you handle in a bad year?",
    "options": [
      "I’d struggle with more than a 10% loss",
      "I could manage up to 20% down",
      "A 30% drop would worry me, but I’d hold on",
      "Even 40% down, I’d stay focused on the long term",
      "I’m fine with losses over 50% — I’m here for the long game"
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  },
  {
    "question": "Your investment drops 15% in a month. What's your move?",
    "options": [
      "Sell everything and take the loss — I’d rather secure what’s left",
      "Sell part of it — I want to lock in some of my money before it drops more",
      "I’d do nothing — I’ll wait and see if it recovers",
      "Invest a little more — might be a smart time to buy",
      "Go all in — I’d put in more money as much as I can while prices are down"
    ],
    "score-map": [
      1,2,3,4,5
    ],
    "images": ["general_investing.png","generate_portfolio.png", "emergency_fund.png", "high_risk.png","independent.png"],
  }
];

int currentEducationModule = 0;

// Variables related to S&P 500 stock view page & stock data generation
bool stopTimer = false;
Map<String, Map<dynamic,dynamic>> allStockData = {};
int selectedStock = 0;
dynamic currentStock;
List<dynamic> selectedStockClosePrices = [];

List<dynamic> currentPlaylistCompanies = [];

Map<String, dynamic> validStocksEgx = {};

// Variables related to playlist generation
bool viewingPlaylist = false;
dynamic currentPlaylist = {};
Map<dynamic, dynamic> stockPercentages = {};

Map<String, dynamic> fullColorsMap = {
  "blueGrey": Colors.blueGrey,
  "green": Colors.green,
  "deepPurpleAccent": Colors.deepPurpleAccent,
  "orange": Colors.orange,
  "lightGreenAccent": Colors.lightGreenAccent,
  "red": Colors.red,
  "redAccent": Colors.redAccent,
  "blue": Colors.blue,
  "black": Colors.black,
  "secondaryColor": secondaryColor,
  "yellow": Colors.yellow,
};

List<String> sectors = [
  'Banks',
  'Basic Resources',
  'Building Materials',
  'Contracting & Construction Engineering',
  'Education Services',
  'Energy & Support Services',
  'Food, Beverages & Tobacco',
  'Healthcare & Pharmaceuticals',
  'IT , Media & Communication',
  //'Industrial Goods & Services',
  'Non-bank financial services',
  'Paper & Packaging',
  'Real Estate',
  'Shipping & Transportation Services',
  'Textile & Durables',
  'Trade & Distributors',
  'Travel & Leisure',
  'Utilities'
];

dynamic educationalContent = {
  'content-amount': 2,
  0: {
    'full-module-title': 'Investing 101',
    'module-title': 'What is a stock?',
    'module-image': 'finance',
    'module-length': 9,
    'paragraphs-length': 5,
    'titles': [
      "What is a Share?",
      "So, What is a Stock?",
      "Why Do Companies Issue Shares?",
      "What’s in It for You as an Investor?",
      "Why Do Stock Prices Go Up or Down?",
    ],
    'paragraphs': [
      "Imagine a company as a big pie. A share is one slice of that pie — a single unit of ownership in the company. The more slices you own, the more of the company you control.\n\nCompanies divide themselves into thousands (or even millions) of these shares to make it easier to raise money and allow many people to invest.",
      "A stock is simply the collection of all the company’s shares available to buy and sell on the stock market. When you buy a stock, you're buying one or more shares, which makes you a partial owner of the company.\n\nThat ownership means you benefit when the company does well — your shares can increase in value, and you might receive profits.",
      "Instead of taking out a loan, companies often issue shares to raise money. This process is called an Initial Public Offering (IPO). It allows the public — people like you — to buy those shares on the stock market.\n\nThe company uses the money to grow, and in return, you get a shot at sharing in its success.",
      "When you own shares (stock), you become a shareholder. This gives you certain benefits:\n\nCapital gains – if the share price rises, you can sell for a profit.\n\nDividends – some companies distribute a portion of their profits to shareholders.\n\nYou're not running the company — but you are part of it.",
      "Stock prices change because of supply and demand — basically, how many people want to buy shares versus how many want to sell them.\n\nWhen more people want to buy a stock than sell it, the price tends to go up.When more people want to sell than buy, the price usually goes down.\n\nThis demand is influenced by:\n\n📈 Company performance – strong earnings, innovation, or growth can attract buyers.\n\n📰 News & events – product launches, scandals, or global news can affect investor behavior.\n\n💰 Market conditions – interest rates, inflation, and the economy play a big role.\n\n😬 Investor emotion – fear, hype, or trends (like on social media) can create price swings.\n\nSo, stock prices move not just because of what a company is worth, but also because of what people are doing in the market — buying or selling."
    ],
    'paragraph-questions': [
      "What is a stock in simple terms?",
      "Why do companies issue stocks?",
      "How do you make money from stocks?",
      "What are dividends, and how do they work?",
      "What are the risks of investing in stocks?",
      "How is trading different from long-term investing?"
    ],
    "questions-length": 5,
    "questions": {
      0: {
        'type': "multiple-choice",
        'question': "If a stock’s price goes up, what’s the most likely reason?",
        'explanation': 'Prices rise when demand outweighs supply',
        'answer': 2,
        'options': [
          "The government ordered a price increase",
          "The company is reducing the number of shares",
          "More investors are buying than selling",
          "The company increased its office size",
        ],
      },
      1: {
        'type': "drag-and-drop",
        'prompt': 'Tap the matching pairs',
        'pairs-keys': [
          'Stock',
          'Share',
          'IPO',
          'Dividend',
          //'Capital Gain'
        ],
        'pairs-values': [
          "A collection of all a company's shares available to trade",
          "A single unit of ownership in a company",
          "When a company issues shares to the public for the first time",
          "A portion of company profits shared with shareholders",
          //"Profit earned when selling a stock for more than you bought it",
        ],
      },
      2: {
        'type': "fill-sentence-gaps",
        'prompt': 'Complete the sentences by selecting the correct word from the list below.',
        'answer': "shares",
        "explanation": "Shares are units of ownership.",
        'sentence': "When you buy a stock, you're actually buying one or more ________ in a company, which gives you partial ownership.",
        'gaps': 1,
        'word-bank': [
          'dividends',
          'shares',
          'IPO',
          'demand',
          "capital gains"
        ],
      },
      3: {
        'type': "true-or-false",
        'prompt': 'Select the true statements only',
        'answer': [0,3],
        'options': [
          'Buying stock means you own part of the company.',
          'Stock prices only change after a company releases financial reports.',
          'Dividends are a guaranteed part of owning any stock.',
          'You can start investing even with a small amount of money.',
        ],
      },
      4: {
        "type": "multiple-choice",
        "question": "You just bought 5 shares of a company. What does this mean?",
        "explanation": "Owning shares means you legally own a part of the company, but you don’t control it.",
        "answer": 2,
        "options": [
          "You now run part of the company",
          "You have access to private company info",
          "You own a small part of the company",
          "You're guaranteed monthly profits"
        ]
      },
    },
  },
  1: {
    'full-module-title': 'Investing 101',
    'module-title': 'Time value of money',
    'module-image': 'fintech',
    'module-length': 10,
    'paragraphs-length': 4,
    'titles': [
      "What is the time value of money (TVM)?",
      "Let's look at an example!",
      "How is TVM calculated?",
      "How is this concept applied in real situations?",
    ],
    'paragraphs': [
      "The Time Value of Money (TVM) is a basic but powerful concept in finance that helps us understand how the value of money changes over time. In simple terms, TVM means that money you have today is worth more than the same amount of money you receive in the future. Why? Because money today can be invested or used to earn more money over time. For example, if someone gives you \$100 today, you could put it in a savings account or invest it, and after one year, it might become \$105. That extra \$5 is the reward for not spending the money right away — it’s called interest or return.",
      "To make this concept more clear, imagine choosing between receiving \$1,000 today or \$1,000 one year from now. Most people would choose to take the money today, and that’s the smarter choice — because if you take it now, you can invest it or use it to make more money. Even if you just leave it in a bank account with a small interest rate, it will grow over time. On the other hand, if you wait a year, you lose the chance to earn anything with that money during that time.",
      "TVM is often calculated using two key ideas: Present Value (PV) and Future Value (FV). Present Value is the value today of a certain amount of money you will receive in the future. Future Value is the amount of money you’ll have in the future if you invest a certain amount today. For example, if you invest \$1,000 today at a 5% annual interest rate, the future value after one year would be \$1,050. These formulas help you decide whether it's better to receive money now or later, and how much future money is actually worth in today’s terms.",
      "This concept is used in many real-life situations. When you take out a loan, save for retirement, or evaluate an investment, TVM plays an important role. It helps businesses and individuals compare different financial options and make better decisions. By understanding TVM, you can make smarter choices about saving, borrowing, and investing your money. Even though the formulas might seem a bit technical at first, the idea behind them is simple: money today has more power than the same amount in the future.",
    ],
    'paragraph-questions': [
      "Why is TVM important?",
      "Why does inflation matter when thinking about the time value of money?"
      "What is the difference between present value and future value?",
      "How does interest (simple vs. compound) affect the value of money over time?",
      "How do you calculate the future value of an investment?",
      "What is a discount rate, and how is it used to calculate present value?",
    ],
    "questions-length": 6,
    "questions": {
      0: {
        'type': "multiple-choice",
        'question': "Why is \$100 today worth more than \$100 received one year from now?",
        'explanation': 'Because you can invest today’s money to earn interest over time',
        'answer': 1,
        'options': [
          "Because of inflation making money more valuable in the future",
          "Because you can invest today’s money to earn interest over time",
          "Because money loses value when saved",
          "Because future money is always guaranteed",
        ],
      },
      1: {
        'type': "multiple-choice",
        'question': "What does the concept of Present Value (PV) help you determine?",
        'explanation': 'The value today of money you will receive in the future',
        'answer': 2,
        'options': [
          "How much money you have saved today",
          "How much money you will need to retire",
          "The value today of money you will receive in the future",
          "The amount of interest you pay on a loan",
        ],
      },
      2: {
        'type': "fill-sentence-gaps",
        'prompt': 'Complete the sentence by selecting the correct word from the list below.',
        'answer': "Time Value",
        "explanation": "Time Value reflects that money today is worth more because it can earn interest.",
        'sentence': "Money available today is more valuable than the same amount in the future because of its earning potential. This concept is known as the ________ of money.",
        'gaps': 1,
        'word-bank': [
          'Future Value',
          'Time Value',
          'Compound Interest',
          'Present Value',
        ],
      },
      3: {
        'type': "fill-sentence-gaps",
        'prompt': 'Complete the sentence by selecting the correct word from the list below.',
        'answer': "Time Value",
        "explanation": "Discounting is the process of finding today’s value of future money.",
        'sentence': "The process of determining how much a future sum of money is worth today is called ________.",
        'gaps': 1,
        'word-bank': [
          'Compounding',
          'Discounting',
          'Saving',
          'Borrowing',
        ],
      },
      4: {
        'type': "true-or-false",
        'prompt': 'Select the true statements only',
        'answer': [0,1,3],
        'options': [
          'The Time Value of Money helps compare the value of money received at different times.',
          'Future Value tells us how much today’s money will be worth in the future.',
          'Present Value increases as the interest rate increases.',
          'Discounting is used to calculate how much a future amount is worth today.',
        ],
      },
      5: {
        'type': "drag-and-drop",
        'prompt': 'Tap the matching pairs',
        'pairs-keys': [
          'Present Value',
          'Future Value',
          'Interest Rate',
          'Discounting',
        ],
        'pairs-values': [
          "Calculating how much future money is worth today",
          "The amount money grows to in the future",
          "The percentage used to calculate growth or discounting",
          "The process of finding present value",
        ],
      },
    },
  },
};

String previousPage = "";
String currentPage = 'home';

Color mainColor = Color(0xFF463cf6);
Color secondaryColor = Color(0xFF13135e);
Color textFieldColor = Colors.grey.withOpacity(0.1);
Color optionColor = secondaryColor.withOpacity(0.06);
double buttonHeight = 50;


List<String> topStocks = ['AAPL','MSFT','AMZN','NVDA','GOOG','TSLA','META','UNH','XOM','LLY'];
final List<Map<String, dynamic>> stockList = [
  {'symbol': 'AAPL', 'name': 'Apple Inc.'},
  {'symbol': 'MSFT', 'name': 'Microsoft'},
  {'symbol': 'AMZN', 'name': 'Amazon'},
  {'symbol': 'NVDA', 'name': 'NVIDIA Corporation'},
  {'symbol': 'GOOG', 'name': 'Alphabet Inc. (Google)'},
  {'symbol': 'TSLA', 'name': 'Tesla, Inc.'},
  {'symbol': 'META', 'name': 'Meta Platforms, Inc. (Facebook)'},
  {'symbol': 'UNH', 'name': 'UnitedHealth Group Incorporated'},
  {'symbol': 'XOM', 'name': 'Exxon Mobil Corporation'},
  {'symbol': 'LLY', 'name': 'Eli Lilly and Company'},
];

final dynamic egx_top_names = [
  {'symbol': 'COMI', 'name': 'CIB'},
  {'symbol': 'SWDY', 'name': 'Sewedy Electric'},
  {'symbol': 'FWRY', 'name': 'Fawry'},
  {'symbol': 'JUFO', 'name': 'Juhayna'},
  {'symbol': 'TMGH', 'name': 'TMG'},
];

final List<dynamic> egx_top_tickers = egx_top_names.map((item) => item['symbol'] as String).toList();

final List<Map<String, dynamic>> egxTopStockList = [
  {'symbol': 'EMFD', 'name': 'Emaar Misr for Development'},
  {'symbol': 'ORHD', 'name': 'Orascom Development Egypt'},
  {'symbol': 'PHDC', 'name': 'Palm Hills Development Company'},
  {'symbol': 'OCDI', 'name': 'SODIC'},
  {'symbol': 'COMI', 'name': 'Commercial International Bank – Egypt (CIB)'},
  {'symbol': 'FWRY', 'name': 'Fawry For Banking Technology And Electronic Payment'},
  {'symbol': 'SWDY', 'name': 'ELSWEDY ELECTRIC'},
  {'symbol': 'CIEB', 'name': 'Credit Agricole Egypt'},
  {'symbol': 'HRHO', 'name': 'EFG Holding'},
  {'symbol': 'TMGH', 'name': 'T M G Holding - Talaat Mostafa Group'},
];

final List<String> topTickersEgx = egxTopStockList.map((item) => item['symbol'] as String).toList();
final List<String> topCompaniesEgx = egxTopStockList.map((item) => item['name'] as String).toList();


final List<Map<String,dynamic>> egxStockList = [
  {'symbol': 'GPPL', 'name': 'Golden Pyramids Plaza'},
  {'symbol': 'MHOT', 'name': 'Misr Hotels'},
  {'symbol': 'EGTS', 'name': 'Egyptian for Tourism Resorts'},
  {'symbol': 'PHTV', 'name': 'Pyramisa Hotels'},
  {'symbol': 'ROTO', 'name': 'Rowad Tourism (Al Rowad)'},
  {'symbol': 'ELWA', 'name': 'El Wadi For International and Investment Development'},
  {'symbol': 'TRTO', 'name': 'TransOceans Tours'},
  {'symbol': 'MTIE', 'name': 'MM Group For Industry And International Trade'},
  {'symbol': 'IFAP', 'name': 'International Agricultural Products'},
  {'symbol': 'ORWE', 'name': 'Oriental Weavers'},
  {'symbol': 'DSCW', 'name': 'Dice Sport & Casual Wear'},
  {'symbol': 'KABO', 'name': 'El Nasr Clothes & Textiles (Kabo)'},
  {'symbol': 'CFGH', 'name': 'Concrete Fashion Group For Commercial & Industrial Investment'},
  {'symbol': 'ACGC', 'name': 'Arab Cotton Ginning'},
  {'symbol': 'APSW', 'name': 'ARAB POLVARA SPINNING & WEAVING CO.'},
  {'symbol': 'ALCN', 'name': 'Alexandria Containers and Goods'},
  {'symbol': 'CSAG', 'name': 'Canal Shipping Agencies'},
  {'symbol': 'ETRS', 'name': 'Egyptian Transport (EGYTRANS)'},
  {'symbol': 'TMGH', 'name': 'T M G Holding - Talaat Mostafa Group'},
  {'symbol': 'EMFD', 'name': 'Emaar Misr for Development'},
  {'symbol': 'ORHD', 'name': 'Orascom Development Egypt'},
  {'symbol': 'PHDC', 'name': 'Palm Hills Development Company'},
  {'symbol': 'OCDI', 'name': 'Sixth of October Development & Investment (SODIC)'},
  {'symbol': 'HELI', 'name': 'Helipolis Housing'},
  {'symbol': 'MASR', 'name': 'Madinet Masr For Housing and Development'},
  {'symbol': 'ZMID', 'name': 'Zahraa Maadi Investment & Development'},
  {'symbol': 'ELKA', 'name': 'El Kahera Housing'},
  {'symbol': 'UNIT', 'name': 'United Housing & Development'},
  {'symbol': 'ARAB', 'name': 'Arab Developers Holding'},
  {'symbol': 'ELSH', 'name': 'El Shams Housing & Urbanization'},
  {'symbol': 'EHDR', 'name': 'Egyptians Housing Development & Reconstruction'},
  {'symbol': 'AMER', 'name': 'Amer Group Holding'},
  {'symbol': 'MENA', 'name': 'Mena Touristic & Real Estate Investment'},
  {'symbol': 'DAPH', 'name': 'Development & Engineering Consultants'},
  {'symbol': 'IDRE', 'name': 'Ismailia Development and Real Estate Co'},
  {'symbol': 'REAC', 'name': 'Reacap Financial Investments'},
  {'symbol': 'UEGC', 'name': 'Elseaed Contracting Real Estate Investment Company SCCD'},
  {'symbol': 'NHPS', 'name': 'National Housing for Professional Syndicates'},
  {'symbol': 'MAAL', 'name': 'Egyptian Gulf Marselia For Real Estate Investment'},
  {'symbol': 'RREI', 'name': 'Arab Real Estate Investment CO. - ALICO'},
  {'symbol': 'OBRI', 'name': 'El Obour Real Estate Investment'},
  {'symbol': 'ICID', 'name': 'International Co For Investment & Development'},
  {'symbol': 'CCRS', 'name': 'Gulf Canadian Real Estate Investment Co.'},
  {'symbol': 'AREH', 'name': 'Egyptian Real Estate Group'},
  {'symbol': 'UNIP', 'name': 'Universal For Paper and Packaging Materials (Unipack)'},
  {'symbol': 'RAKT', 'name': 'Rakta Paper Manufacturing'},
  {'symbol': 'EPPK', 'name': 'El Ahram Co. For Printing And Packing'},
  {'symbol': 'HRHO', 'name': 'EFG Holding'},
  {'symbol': 'BTFH', 'name': 'Beltone Holding'},
  {'symbol': 'EKHO', 'name': 'Egyptian Kuwaiti Holding'},
  {'symbol': 'RAYA', 'name': 'Raya Holding For Financial Investments'},
  {'symbol': 'EKHOA', 'name': 'Egyptian Kuwaiti Holding - EGP'},
  {'symbol': 'BINV', 'name': 'B Investments Holding'},
  {'symbol': 'CICH', 'name': 'CI Capital Holding For Financial Investments'},
  {'symbol': 'CNFN', 'name': 'Contact Financial Holding'},
  {'symbol': 'MOIN', 'name': 'Mohandes Insurance'},
  {'symbol': 'CCAP',
    'name': 'QALA For Financial Investments - Citadel Capital'},
  {'symbol': 'OFH', 'name': 'Orascom Financial Holding'},
  {'symbol': 'NAHO', 'name': 'Naeem Holding'},
  {'symbol': 'AMIA', 'name': 'Arab Moltaka Investments Co'},
  {'symbol': 'ATLC', 'name': 'Al Tawfeek Leasing Company - A.T.LEASE'},
  {'symbol': 'ODIN', 'name': 'ODIN Investments'},
  {'symbol': 'AIH', 'name': 'Arabia Investments Holding'},
  {'symbol': 'ASPI',
    'name': 'Aspire Capital Holding For Financial Investments'},
  {'symbol': 'EASB',
    'name': 'Egyptian Arabian (Themar) Comp. For Securities & Bonds Brok. EAC'},
  {'symbol': 'PRMH', 'name': 'Prime Holding'},
  {'symbol': 'ANFI',
    'name': 'Alexandria National Company for Financial Investment'},
  {'symbol': 'GRCA', 'name': 'Grand Investment Capital'},
  {'symbol': 'EOSB', 'name': 'El Orouba Securities Brokerage'},
  {'symbol': 'DEIN', 'name': 'Delta Insurance'},
  {'symbol': 'ICLE', 'name': 'International Company For Leasing (IncoLEASE)'},
  {'symbol': 'SWDY', 'name': 'ELSWEDY ELECTRIC'},
  {'symbol': 'GBCO', 'name': 'GB Corp'},
  {'symbol': 'ELEC', 'name': 'Electro Cable Egypt'},
  {'symbol': 'DTPP', 'name': 'Delta For Printing & Packaging'},
  {'symbol': 'EEII', 'name': 'El Arabia Engineering Industries'},
  {'symbol': 'ETEL', 'name': 'Telecom Egypt'},
  {'symbol': 'EFIH', 'name': 'E-finance For Digital and Financial Investments'},
  {'symbol': 'FWRY', 'name': 'Fawry For Banking Technology And Electronic Payment'},
  {'symbol': 'EGSA', 'name': 'Egyptian Satellites (NileSat)'},
  {'symbol': 'OIH', 'name': 'Orascom Investment Holding'},
  {'symbol': 'RACC', 'name': 'Raya Customer Experience'},
  {'symbol': 'CLHO', 'name': 'Cleopatra Hospital Company'},
  {'symbol': 'ISPH', 'name': 'Ibnsina Pharma'},
  {'symbol': 'PHAR', 'name': 'Egyptian International Pharmaceuticals (EIPICO)'},
  {'symbol': 'RMDA',
    'name': 'Tenth Of Ramadan Pharmaceutical Industries & Diagnostic - Rameda'},
  {'symbol': 'MIPH', 'name': 'Minapharm Pharmaceuticals'},
  {'symbol': 'AMES', 'name': 'Alexandria New Medical Center'},
  {'symbol': 'NINH', 'name': 'Nozha International Hospital'},
  {'symbol': 'MPCI', 'name': 'Memphis Pharmaceuticals'},
  {'symbol': 'NIPH',
    'name': 'El-Nile Co. For Pharmaceuticals And Chemical Industries'},
  {'symbol': 'OCPH', 'name': 'October Pharma'},
  {'symbol': 'MCRO', 'name': 'Macro Group Pharmaceuticals - Macro Capital'},
  {'symbol': 'ADCI', 'name': 'Arab Pharmaceuticals'},
  {'symbol': 'MEPA', 'name': 'Medical Packaging Company'},
  {'symbol': 'SPMD', 'name': 'Speed Medical'},
  {'symbol': 'SIPC',
    'name': 'Sabaa International Company for Pharmaceutical and Chemical'},
  {'symbol': 'EAST', 'name': 'Eastern Company'},
  {'symbol': 'JUFO', 'name': 'Juhayna Food Industries'},
  {'symbol': 'EFID', 'name': 'Edita Food Industries S.A.E'},
  {'symbol': 'POUL', 'name': 'Cairo Poultry'},
  {'symbol': 'OLFI', 'name': 'Obour Land For Food Industries'},
  {'symbol': 'DOMT', 'name': 'Arabian Food Industries DOMTY'},
  {'symbol': 'GSSC', 'name': 'General Silos & Storage'},
  {'symbol': 'AJWA', 'name': 'AJWA for Food Industries company Egypt'},
  {'symbol': 'ADPC', 'name': 'The Arab Dairy Products Co. Arab Dairy – Panda'},
  {'symbol': 'INFI', 'name': 'Ismailia National Food Industries'},
  {'symbol': 'MPCO', 'name': 'Mansourah Poultry'},
  {'symbol': 'COSG', 'name': 'Cairo Oils & Soap'},
  {'symbol': 'AFMC', 'name': 'Alexandria Flour Mills'},
  {'symbol': 'ISMA', 'name': 'Ismailia Misr Poultry'},
  {'symbol': 'ZEOT', 'name': 'Extracted Oils'},
  {'symbol': 'ELNA', 'name': 'El Nasr For Manufacturing Agricultural Crops'},
  {'symbol': 'EPCO', 'name': 'Egypt for Poultry'},
  {'symbol': 'AMOC', 'name': 'Alexandria Mineral Oils Company'},
  {'symbol': 'MOIL', 'name': 'Maridive & Oil Services'},
  {'symbol': 'SCTS', 'name': 'Sues Canal Company For Technology Settling'},
  {'symbol': 'CIRA',
    'name': 'Cairo For Investment And Real Estate Developments – CIRA Edu'},
  {'symbol': 'TALM', 'name': 'Taaleem Management Services'},
  {'symbol': 'ENGC', 'name': 'Engineering Industries (ICON)'},
  {'symbol': 'GGCC', 'name': 'Giza General Contracting'},
  {'symbol': 'NCCW', 'name': 'Nasr Company for Civil Works'},
  {'symbol': 'EALR', 'name': 'El Arabia for Land Reclamation'},
  {'symbol': 'AALR',
    'name': 'General Company For Land Reclamation, Development & Reconstruction'},
  {'symbol': 'EIUD', 'name': 'Egyptians For Investment & Urban Development'},
  {'symbol': 'COPR',
    'name': 'Copper For Commercial Investment & Real Estate Development'},
  {'symbol': 'ARCC', 'name': 'Arabian Cement Company'},
  {'symbol': 'SCEM', 'name': 'Sinai Cement'},
  {'symbol': 'MBSC', 'name': 'Misr Beni Suef Cement'},
  {'symbol': 'MCQE', 'name': 'Misr Cement (Qena)'},
  {'symbol': 'SVCE', 'name': 'South Valley Cement'},
  {'symbol': 'LCSW', 'name': 'Lecico Egypt'},
  {'symbol': 'ECAP', 'name': 'El Ezz Porcelain (Gemma)'},
  {'symbol': 'CERA', 'name': 'The Arab Ceramic CO.- Ceramica Remas'},
  {'symbol': 'PRCL', 'name': 'Ceramic & Porcelain (Sheeni)'},
  {'symbol': 'ARVA', 'name': 'Arab Valves Company'},
  {'symbol': 'MFPC', 'name': 'Misr Fertilizers Production Company – Mopco'},
  {'symbol': 'EGAL', 'name': 'Egypt Aluminum'},
  {'symbol': 'ABUK', 'name': 'Abou Kir Fertilizers'},
  {'symbol': 'SKPC', 'name': 'Sidi Kerir Petrochemicals – SIDPEC'},
  {'symbol': 'EGCH', 'name': 'Egyptian Chemical Industries (Kima)'},
  {'symbol': 'ATQA', 'name': 'Misr National Steel – Ataqa'},
  {'symbol': 'EFIC', 'name': 'Egyptian Financial & Industrial'},
  {'symbol': 'MICH', 'name': 'Misr Chemical Industries'},
  {'symbol': 'KZPC', 'name': 'Kafr El Zayat Pesticides'},
  {'symbol': 'ASCM', 'name': 'ASEC Company For Mining – ASCOM'},
  {'symbol': 'ALUM', 'name': 'Arab Aluminum'},
  {'symbol': 'COMI', 'name': 'Commercial International Bank – Egypt (CIB)'},
  {'symbol': 'HDBK', 'name': 'Housing & Development Bank'},
  {'symbol': 'ADIB', 'name': 'Abu Dhabi Islamic Bank – Egypt'},
  {'symbol': 'CIEB', 'name': 'Credit Agricole Egypt'},
  {'symbol': 'FAITA', 'name': 'Faisal Islamic Bank of Egypt – In USD'},
  {'symbol': 'EXPA', 'name': 'Export Development Bank of Egypt'},
  {'symbol': 'CANA', 'name': 'Suez Canal Bank S.A.E.'},
  {'symbol': 'SAUD', 'name': 'Al Baraka Bank Egypt'},
  {'symbol': 'EGBE', 'name': 'Egyptian Gulf Bank'},
  {'symbol': 'FAIT', 'name': 'Faisal Islamic Bank of Egypt – In EGP'},
  {'symbol': 'SAIB', 'name': 'Societe Arabe Internationale De Banque S.A.E.'},
  {'symbol': 'EGAS', 'name': 'Natural Gas & Mining Project (Egypt Gas)'}
];

List<String> validStocks = egxStockList.map((item) => item['symbol'] as String).toList();

final List<Map<String, dynamic>> sp500StockList = [
{'symbol': 'MMM', 'name': '3M Company'},
{'symbol': 'AOS', 'name': 'A. O. Smith Corporation'},
{'symbol': 'ABT', 'name': 'Abbott Laboratories'},
{'symbol': 'ABBV', 'name': 'AbbVie Inc.'},
{'symbol': 'ACN', 'name': 'Accenture plc'},
{'symbol': 'ADBE', 'name': 'Adobe Inc.'},
{'symbol': 'AMD', 'name': 'Advanced Micro Devices, Inc.'},
{'symbol': 'AES', 'name': 'The AES Corporation'},
{'symbol': 'AFL', 'name': 'Aflac Incorporated'},
{'symbol': 'A', 'name': 'Agilent Technologies, Inc.'},
{'symbol': 'APD', 'name': 'Air Products and Chemicals, Inc.'},
{'symbol': 'ABNB', 'name': 'Airbnb, Inc.'},
{'symbol': 'AKAM', 'name': 'Akamai Technologies, Inc.'},
{'symbol': 'ALB', 'name': 'Albemarle Corporation'},
{'symbol': 'ARE', 'name': 'Alexandria Real Estate Equities, Inc.'},
{'symbol': 'ALGN', 'name': 'Align Technology, Inc.'},
{'symbol': 'ALLE', 'name': 'Allegion plc'},
{'symbol': 'LNT', 'name': 'Alliant Energy Corporation'},
{'symbol': 'ALL', 'name': 'The Allstate Corporation'},
{'symbol': 'GOOG', 'name': 'Alphabet Inc.'},
{'symbol': 'MO', 'name': 'Altria Group, Inc.'},
{'symbol': 'AMZN', 'name': 'Amazon.com, Inc.'},
{'symbol': 'AMCR', 'name': 'Amcor plc'},
{'symbol': 'AEE', 'name': 'Ameren Corporation'},
{'symbol': 'AEP', 'name': 'American Electric Power Company, Inc.'},
{'symbol': 'AXP', 'name': 'American Express Company'},
{'symbol': 'AIG', 'name': 'American International Group, Inc.'},
{'symbol': 'AMT', 'name': 'American Tower Corporation'},
{'symbol': 'AWK', 'name': 'American Water Works Company, Inc.'},
{'symbol': 'AMP', 'name': 'Ameriprise Financial, Inc.'},
{'symbol': 'AME', 'name': 'AMETEK, Inc.'},
{'symbol': 'AMGN', 'name': 'Amgen Inc.'},
{'symbol': 'APH', 'name': 'Amphenol Corporation'},
{'symbol': 'ADI', 'name': 'Analog Devices, Inc.'},
{'symbol': 'ANSS', 'name': 'ANSYS, Inc.'},
{'symbol': 'AON', 'name': 'Aon plc'},
{'symbol': 'APA', 'name': 'APA Corporation'},
{'symbol': 'APO', 'name': 'Apollo Global Management, Inc.'},
{'symbol': 'AAPL', 'name': 'Apple Inc.'},
{'symbol': 'AMAT', 'name': 'Applied Materials, Inc.'},
{'symbol': 'APTV', 'name': 'Aptiv PLC'},
{'symbol': 'ACGL', 'name': 'Arch Capital Group Ltd.'},
{'symbol': 'ADM', 'name': 'Archer-Daniels-Midland Company'},
{'symbol': 'ANET', 'name': 'Arista Networks Inc'},
{'symbol': 'AJG', 'name': 'Arthur J. Gallagher & Co.'},
{'symbol': 'AIZ', 'name': 'Assurant, Inc.'},
{'symbol': 'T', 'name': 'AT&T Inc.'},
{'symbol': 'ATO', 'name': 'Atmos Energy Corporation'},
{'symbol': 'ADSK', 'name': 'Autodesk, Inc.'},
{'symbol': 'ADP', 'name': 'Automatic Data Processing, Inc.'},
{'symbol': 'AZO', 'name': 'AutoZone, Inc.'},
{'symbol': 'AVB', 'name': 'AvalonBay Communities, Inc.'},
{'symbol': 'AVY', 'name': 'Avery Dennison Corporation'},
{'symbol': 'AXON', 'name': 'Axon Enterprise, Inc.'},
{'symbol': 'BKR', 'name': 'Baker Hughes Company'},
{'symbol': 'BALL', 'name': 'Ball Corporation'},
{'symbol': 'BAC', 'name': 'Bank of America Corporation'},
{'symbol': 'BAX', 'name': 'Baxter International Inc.'},
{'symbol': 'BDX', 'name': 'Becton, Dickinson and Company'},
{'symbol': 'BBY', 'name': 'Best Buy Co., Inc.'},
{'symbol': 'TECH', 'name': 'Bio-Techne Corporation'},
{'symbol': 'BIIB', 'name': 'Biogen Inc.'},
{'symbol': 'BLK', 'name': 'BlackRock, Inc.'},
{'symbol': 'BX', 'name': 'Blackstone Inc.'},
{'symbol': 'BK', 'name': 'The Bank of New York Mellon Corporation'},
{'symbol': 'BA', 'name': 'The Boeing Company'},
{'symbol': 'BKNG', 'name': 'Booking Holdings Inc.'},
{'symbol': 'BWA', 'name': 'BorgWarner Inc.'},
{'symbol': 'BSX', 'name': 'Boston Scientific Corporation'},
{'symbol': 'BMY', 'name': 'Bristol-Myers Squibb Company'},
{'symbol': 'AVGO', 'name': 'Broadcom Inc.'},
{'symbol': 'BR', 'name': 'Broadridge Financial Solutions, Inc.'},
{'symbol': 'BRO', 'name': 'Brown & Brown, Inc.'},
{'symbol': 'BLDR', 'name': 'Builders FirstSource, Inc.'},
{'symbol': 'BG', 'name': 'Bunge Global SA'},
{'symbol': 'BXP', 'name': 'BXP, Inc.'},
{'symbol': 'CHRW', 'name': 'C.H. Robinson Worldwide, Inc.'},
{'symbol': 'CDNS', 'name': 'Cadence Design Systems, Inc.'},
{'symbol': 'CZR', 'name': 'Caesars Entertainment, Inc.'},
{'symbol': 'CPT', 'name': 'Camden Property Trust'},
{'symbol': 'CPB', 'name': "The Campbell's Company"},
{'symbol': 'COF', 'name': 'Capital One Financial Corporation'},
{'symbol': 'CAH', 'name': 'Cardinal Health, Inc.'},
{'symbol': 'KMX', 'name': 'CarMax, Inc.'},
{'symbol': 'CCL', 'name': 'Carnival Corporation & plc'},
{'symbol': 'CARR', 'name': 'Carrier Global Corporation'},
{'symbol': 'CAT', 'name': 'Caterpillar Inc.'},
{'symbol': 'CBOE', 'name': 'Cboe Global Markets, Inc.'},
{'symbol': 'CBRE', 'name': 'CBRE Group, Inc.'},
{'symbol': 'CDW', 'name': 'CDW Corporation'},
{'symbol': 'CE', 'name': 'Celanese Corporation'},
{'symbol': 'COR', 'name': 'Cencora, Inc.'},
{'symbol': 'CNC', 'name': 'Centene Corporation'},
{'symbol': 'CNP', 'name': 'CenterPoint Energy, Inc.'},
{'symbol': 'CF', 'name': 'CF Industries Holdings, Inc.'},
{'symbol': 'CRL', 'name': 'Charles River Laboratories International, Inc.'},
{'symbol': 'SCHW', 'name': 'The Charles Schwab Corporation'},
{'symbol': 'CHTR', 'name': 'null'},
{'symbol': 'CVX', 'name': 'Chevron Corporation'},
{'symbol': 'CMG', 'name': 'Chipotle Mexican Grill, Inc.'},
{'symbol': 'CB', 'name': 'Chubb Limited'},
{'symbol': 'CHD', 'name': 'Church & Dwight Co., Inc.'},
{'symbol': 'CI', 'name': 'The Cigna Group'},
{'symbol': 'CINF', 'name': 'Cincinnati Financial Corporation'},
{'symbol': 'CTAS', 'name': 'Cintas Corporation'},
{'symbol': 'CSCO', 'name': 'Cisco Systems, Inc.'},
{'symbol': 'C', 'name': 'Citigroup Inc.'},
{'symbol': 'CFG', 'name': 'Citizens Financial Group, Inc.'},
{'symbol': 'CLX', 'name': 'The Clorox Company'},
{'symbol': 'CME', 'name': 'CME Group Inc.'},
{'symbol': 'CMS', 'name': 'CMS Energy Corporation'},
{'symbol': 'KO', 'name': 'The Coca-Cola Company'},
{'symbol': 'CTSH', 'name': 'Cognizant Technology Solutions Corporation'},
{'symbol': 'CL', 'name': 'Colgate-Palmolive Company'},
{'symbol': 'CMCSA', 'name': 'Comcast Corporation'},
{'symbol': 'CAG', 'name': 'Conagra Brands, Inc.'},
{'symbol': 'COP', 'name': 'ConocoPhillips'},
{'symbol': 'ED', 'name': 'Consolidated Edison, Inc.'},
{'symbol': 'STZ', 'name': 'Constellation Brands, Inc.'},
{'symbol': 'CEG', 'name': 'Constellation Energy Corporation'},
{'symbol': 'COO', 'name': 'The Cooper Companies, Inc.'},
{'symbol': 'CPRT', 'name': 'Copart, Inc.'},
{'symbol': 'GLW', 'name': 'Corning Incorporated'},
{'symbol': 'CPAY', 'name': 'Corpay, Inc.'},
{'symbol': 'CTVA', 'name': 'Corteva, Inc.'},
{'symbol': 'CSGP', 'name': 'CoStar Group, Inc.'},
{'symbol': 'COST', 'name': 'Costco Wholesale Corporation'},
{'symbol': 'CTRA', 'name': 'Coterra Energy Inc.'},
{'symbol': 'CRWD', 'name': 'CrowdStrike Holdings, Inc.'},
{'symbol': 'CCI', 'name': 'Crown Castle Inc.'},
{'symbol': 'CSX', 'name': 'CSX Corporation'},
{'symbol': 'CMI', 'name': 'Cummins Inc.'},
{'symbol': 'CVS', 'name': 'CVS Health Corporation'},
{'symbol': 'DHR', 'name': 'Danaher Corporation'},
{'symbol': 'DRI', 'name': 'Darden Restaurants, Inc.'},
{'symbol': 'DVA', 'name': 'DaVita Inc.'},
{'symbol': 'DAY', 'name': 'Dayforce Inc'},
{'symbol': 'DECK', 'name': 'Deckers Outdoor Corporation'},
{'symbol': 'DE', 'name': 'Deere & Company'},
{'symbol': 'DELL', 'name': 'Dell Technologies Inc.'},
{'symbol': 'DAL', 'name': 'Delta Air Lines, Inc.'},
{'symbol': 'DVN', 'name': 'Devon Energy Corporation'},
{'symbol': 'DXCM', 'name': 'DexCom, Inc.'},
{'symbol': 'FANG', 'name': 'Diamondback Energy, Inc.'},
{'symbol': 'DLR', 'name': 'Digital Realty Trust, Inc.'},
{'symbol': 'DFS', 'name': 'Discover Financial Services'},
{'symbol': 'DG', 'name': 'Dollar General Corporation'},
{'symbol': 'DLTR', 'name': 'Dollar Tree, Inc.'},
{'symbol': 'D', 'name': 'Dominion Energy, Inc.'},
{'symbol': 'DPZ', 'name': "Domino's Pizza, Inc."},
{'symbol': 'DOV', 'name': 'Dover Corporation'},
{'symbol': 'DOW', 'name': 'Dow Inc.'},
{'symbol': 'DHI', 'name': 'D.R. Horton, Inc.'},
{'symbol': 'DTE', 'name': 'DTE Energy Company'},
{'symbol': 'DUK', 'name': 'Duke Energy Corporation'},
{'symbol': 'DD', 'name': 'DuPont de Nemours, Inc.'},
{'symbol': 'EMN', 'name': 'Eastman Chemical Company'},
{'symbol': 'ETN', 'name': 'Eaton Corporation plc'},
{'symbol': 'EBAY', 'name': 'eBay Inc.'},
{'symbol': 'ECL', 'name': 'Ecolab Inc.'},
{'symbol': 'EIX', 'name': 'Edison International'},
{'symbol': 'EW', 'name': 'Edwards Lifesciences Corporation'},
{'symbol': 'EA', 'name': 'Electronic Arts Inc.'},
{'symbol': 'ELV', 'name': 'Elevance Health, Inc.'},
{'symbol': 'EMR', 'name': 'Emerson Electric Co.'},
{'symbol': 'ENPH', 'name': 'Enphase Energy, Inc.'},
{'symbol': 'ETR', 'name': 'Entergy Corporation'},
{'symbol': 'EOG', 'name': 'EOG Resources, Inc.'},
{'symbol': 'EPAM', 'name': 'EPAM Systems, Inc.'},
{'symbol': 'EQT', 'name': 'EQT Corporation'},
{'symbol': 'EFX', 'name': 'Equifax Inc.'},
{'symbol': 'EQIX', 'name': 'Equinix, Inc.'},
{'symbol': 'EQR', 'name': 'Equity Residential'},
{'symbol': 'ERIE', 'name': 'Erie Indemnity Company'},
{'symbol': 'ESS', 'name': 'Essex Property Trust, Inc.'},
{'symbol': 'EL', 'name': 'The Estée Lauder Companies Inc.'},
{'symbol': 'EG', 'name': 'Everest Group, Ltd.'},
{'symbol': 'EVRG', 'name': 'Evergy, Inc.'},
{'symbol': 'ES', 'name': 'Eversource Energy'},
{'symbol': 'EXC', 'name': 'Exelon Corporation'},
{'symbol': 'EXPE', 'name': 'Expedia Group, Inc.'},
{'symbol': 'EXPD', 'name': 'Expeditors International of Washington, Inc.'},
{'symbol': 'EXR', 'name': 'Extra Space Storage Inc.'},
{'symbol': 'XOM', 'name': 'Exxon Mobil Corporation'},
{'symbol': 'FFIV', 'name': 'F5, Inc.'},
{'symbol': 'FDS', 'name': 'FactSet Research Systems Inc.'},
{'symbol': 'FICO', 'name': 'Fair Isaac Corporation'},
{'symbol': 'FAST', 'name': 'Fastenal Company'},
{'symbol': 'FRT', 'name': 'Federal Realty Investment Trust'},
{'symbol': 'FDX', 'name': 'FedEx Corporation'},
{'symbol': 'FIS', 'name': 'Fidelity National Information Services, Inc.'},
{'symbol': 'FITB', 'name': 'Fifth Third Bancorp'},
{'symbol': 'FSLR', 'name': 'First Solar, Inc.'},
{'symbol': 'FE', 'name': 'FirstEnergy Corp.'},
{'symbol': 'FI', 'name': 'Fiserv, Inc.'},
{'symbol': 'FMC', 'name': 'FMC Corporation'},
{'symbol': 'F', 'name': 'Ford Motor Company'},
{'symbol': 'FTNT', 'name': 'Fortinet, Inc.'},
{'symbol': 'FTV', 'name': 'Fortive Corporation'},
{'symbol': 'FOXA', 'name': 'Fox Corporation'},
{'symbol': 'FOX', 'name': 'Fox Corporation'},
{'symbol': 'BEN', 'name': 'Franklin Resources, Inc.'},
{'symbol': 'FCX', 'name': 'Freeport-McMoRan Inc.'},
{'symbol': 'GRMN', 'name': 'Garmin Ltd.'},
{'symbol': 'IT', 'name': 'Gartner, Inc.'},
{'symbol': 'GE', 'name': 'GE Aerospace'},
{'symbol': 'GEHC', 'name': 'GE HealthCare Technologies Inc.'},
{'symbol': 'GEN', 'name': 'Gen Digital Inc.'},
{'symbol': 'GNRC', 'name': 'Generac Holdings Inc.'},
{'symbol': 'GD', 'name': 'General Dynamics Corporation'},
{'symbol': 'GIS', 'name': 'General Mills, Inc.'},
{'symbol': 'GM', 'name': 'General Motors Company'},
{'symbol': 'GPC', 'name': 'Genuine Parts Company'},
{'symbol': 'GILD', 'name': 'Gilead Sciences, Inc.'},
{'symbol': 'GPN', 'name': 'Global Payments Inc.'},
{'symbol': 'GL', 'name': 'Globe Life Inc.'},
{'symbol': 'GDDY', 'name': 'GoDaddy Inc.'},
{'symbol': 'GS', 'name': 'The Goldman Sachs Group, Inc.'},
{'symbol': 'HAL', 'name': 'Halliburton Company'},
{'symbol': 'HIG', 'name': 'The Hartford Insurance Group, Inc.'},
{'symbol': 'HAS', 'name': 'Hasbro, Inc.'},
{'symbol': 'HCA', 'name': 'HCA Healthcare, Inc.'},
{'symbol': 'DOC', 'name': 'Healthpeak Properties, Inc.'},
{'symbol': 'HSIC', 'name': 'Henry Schein, Inc.'},
{'symbol': 'HSY', 'name': 'The Hershey Company'},
{'symbol': 'HES', 'name': 'Hess Corporation'},
{'symbol': 'HPE', 'name': 'Hewlett Packard Enterprise Company'},
{'symbol': 'HLT', 'name': 'Hilton Worldwide Holdings Inc.'},
{'symbol': 'HOLX', 'name': 'Hologic, Inc.'},
{'symbol': 'HD', 'name': 'The Home Depot, Inc.'},
{'symbol': 'HON', 'name': 'Honeywell International Inc.'},
{'symbol': 'HRL', 'name': 'Hormel Foods Corporation'},
{'symbol': 'HST', 'name': 'Host Hotels & Resorts, Inc.'},
{'symbol': 'HWM', 'name': 'Howmet Aerospace Inc.'},
{'symbol': 'HPQ', 'name': 'HP Inc.'},
{'symbol': 'HUBB', 'name': 'Hubbell Incorporated'},
{'symbol': 'HUM', 'name': 'Humana Inc.'},
{'symbol': 'HBAN', 'name': 'Huntington Bancshares Incorporated'},
{'symbol': 'HII', 'name': 'Huntington Ingalls Industries, Inc.'},
{'symbol': 'IBM', 'name': 'International Business Machines Corporation'},
{'symbol': 'IEX', 'name': 'IDEX Corporation'},
{'symbol': 'IDXX', 'name': 'IDEXX Laboratories, Inc.'},
{'symbol': 'ITW', 'name': 'Illinois Tool Works Inc.'},
{'symbol': 'INCY', 'name': 'Incyte Corporation'},
{'symbol': 'IR', 'name': 'Ingersoll Rand Inc.'},
{'symbol': 'PODD', 'name': 'Insulet Corporation'},
{'symbol': 'INTC', 'name': 'Intel Corporation'},
{'symbol': 'ICE', 'name': 'Intercontinental Exchange, Inc.'},
{'symbol': 'IFF', 'name': 'International Flavors & Fragrances Inc.'},
{'symbol': 'IP', 'name': 'International Paper Company'},
{'symbol': 'IPG', 'name': 'The Interpublic Group of Companies, Inc.'},
{'symbol': 'INTU', 'name': 'Intuit Inc.'},
{'symbol': 'ISRG', 'name': 'Intuitive Surgical, Inc.'},
{'symbol': 'IVZ', 'name': 'Invesco Ltd.'},
{'symbol': 'INVH', 'name': 'Invitation Homes Inc.'},
{'symbol': 'IQV', 'name': 'IQVIA Holdings Inc.'},
{'symbol': 'IRM', 'name': 'Iron Mountain Incorporated'},
{'symbol': 'JBHT', 'name': 'J.B. Hunt Transport Services, Inc.'},
{'symbol': 'JBL', 'name': 'Jabil Inc.'},
{'symbol': 'JKHY', 'name': 'Jack Henry & Associates, Inc.'},
{'symbol': 'J', 'name': 'Jacobs Solutions Inc.'},
{'symbol': 'JNJ', 'name': 'Johnson & Johnson'},
{'symbol': 'JCI', 'name': 'Johnson Controls International plc'},
{'symbol': 'JPM', 'name': 'JPMorgan Chase & Co.'},
{'symbol': 'JNPR', 'name': 'Juniper Networks, Inc.'},
{'symbol': 'K', 'name': 'Kellanova'},
{'symbol': 'KDP', 'name': 'Keurig Dr Pepper Inc.'},
{'symbol': 'KEY', 'name': 'KeyCorp'},
{'symbol': 'KEYS', 'name': 'Keysight Technologies, Inc.'},
{'symbol': 'KMB', 'name': 'Kimberly-Clark Corporation'},
{'symbol': 'KIM', 'name': 'Kimco Realty Corporation'},
{'symbol': 'KMI', 'name': 'Kinder Morgan, Inc.'},
{'symbol': 'KKR', 'name': 'KKR & Co. Inc.'},
{'symbol': 'KLAC', 'name': 'KLA Corporation'},
{'symbol': 'KHC', 'name': 'The Kraft Heinz Company'},
{'symbol': 'KR', 'name': 'The Kroger Co.'},
{'symbol': 'LHX', 'name': 'L3Harris Technologies, Inc.'},
{'symbol': 'LH', 'name': 'Labcorp Holdings Inc.'},
{'symbol': 'LRCX', 'name': 'Lam Research Corporation'},
{'symbol': 'LW', 'name': 'Lamb Weston Holdings, Inc.'},
{'symbol': 'LVS', 'name': 'Las Vegas Sands Corp.'},
{'symbol': 'LDOS', 'name': 'Leidos Holdings, Inc.'},
{'symbol': 'LEN', 'name': 'Lennar Corporation'},
{'symbol': 'LII', 'name': 'Lennox International Inc.'},
{'symbol': 'LLY', 'name': 'Eli Lilly and Company'},
{'symbol': 'LIN', 'name': 'Linde plc'},
{'symbol': 'LYV', 'name': 'Live Nation Entertainment, Inc.'},
{'symbol': 'LKQ', 'name': 'LKQ Corporation'},
{'symbol': 'LMT', 'name': 'Lockheed Martin Corporation'},
{'symbol': 'L', 'name': 'Loews Corporation'},
{'symbol': 'LOW', 'name': "Lowe's Companies, Inc."},
{'symbol': 'LULU', 'name': 'Lululemon Athletica Inc.'},
{'symbol': 'LYB', 'name': 'LyondellBasell Industries N.V.'},
{'symbol': 'MTB', 'name': 'M&T Bank Corporation'},
{'symbol': 'MPC', 'name': 'Marathon Petroleum Corporation'},
{'symbol': 'MKTX', 'name': 'MarketAxess Holdings Inc.'},
{'symbol': 'MAR', 'name': 'Marriott International, Inc.'},
{'symbol': 'MMC', 'name': 'Marsh & McLennan Companies, Inc.'},
{'symbol': 'MLM', 'name': 'Martin Marietta Materials, Inc.'},
{'symbol': 'MAS', 'name': 'Masco Corporation'},
{'symbol': 'MA', 'name': 'Mastercard Incorporated'},
{'symbol': 'MTCH', 'name': 'Match Group, Inc.'},
{'symbol': 'MKC', 'name': 'McCormick & Company, Incorporated'},
{'symbol': 'MCD', 'name': "McDonald's Corporation"},
{'symbol': 'MCK', 'name': 'McKesson Corporation'},
{'symbol': 'MDT', 'name': 'Medtronic plc'},
{'symbol': 'MRK', 'name': 'Merck & Co., Inc.'},
{'symbol': 'META', 'name': 'Meta Platforms, Inc.'},
{'symbol': 'MET', 'name': 'MetLife, Inc.'},
{'symbol': 'MTD', 'name': 'Mettler-Toledo International Inc.'},
{'symbol': 'MGM', 'name': 'MGM Resorts International'},
{'symbol': 'MCHP', 'name': 'Microchip Technology Incorporated'},
{'symbol': 'MU', 'name': 'Micron Technology, Inc.'},
{'symbol': 'MSFT', 'name': 'Microsoft'},
{'symbol': 'MAA', 'name': 'Mid-America Apartment Communities, Inc.'},
{'symbol': 'MRNA', 'name': 'Moderna, Inc.'},
{'symbol': 'MHK', 'name': 'Mohawk Industries, Inc.'},
{'symbol': 'MOH', 'name': 'Molina Healthcare, Inc.'},
{'symbol': 'TAP', 'name': 'Molson Coors Beverage Company'},
{'symbol': 'MDLZ', 'name': 'Mondelez International, Inc.'},
{'symbol': 'MPWR', 'name': 'Monolithic Power Systems, Inc.'},
{'symbol': 'MNST', 'name': 'Monster Beverage Corporation'},
{'symbol': 'MCO', 'name': "Moody's Corporation"},
{'symbol': 'MS', 'name': 'Morgan Stanley'},
{'symbol': 'MOS', 'name': 'The Mosaic Company'},
{'symbol': 'MSI', 'name': 'Motorola Solutions, Inc.'},
{'symbol': 'MSCI', 'name': 'MSCI Inc.'},
{'symbol': 'NDAQ', 'name': 'Nasdaq, Inc.'},
{'symbol': 'NTAP', 'name': 'NetApp, Inc.'},
{'symbol': 'NFLX', 'name': 'Netflix, Inc.'},
{'symbol': 'NEM', 'name': 'Newmont Corporation'},
{'symbol': 'NWSA', 'name': 'News Corporation'},
{'symbol': 'NWS', 'name': 'News Corporation'},
{'symbol': 'NEE', 'name': 'NextEra Energy, Inc.'},
{'symbol': 'NKE', 'name': 'NIKE, Inc.'},
{'symbol': 'NI', 'name': 'NiSource Inc.'},
{'symbol': 'NDSN', 'name': 'Nordson Corporation'},
{'symbol': 'NSC', 'name': 'Norfolk Southern Corporation'},
{'symbol': 'NTRS', 'name': 'Northern Trust Corporation'},
{'symbol': 'NOC', 'name': 'Northrop Grumman Corporation'},
{'symbol': 'NCLH', 'name': 'Norwegian Cruise Line Holdings Ltd.'},
{'symbol': 'NRG', 'name': 'NRG Energy, Inc.'},
{'symbol': 'NUE', 'name': 'Nucor Corporation'},
{'symbol': 'NVDA', 'name': 'NVIDIA Corporation'},
{'symbol': 'NVR', 'name': 'NVR, Inc.'},
{'symbol': 'NXPI', 'name': 'NXP Semiconductors N.V.'},
{'symbol': 'ORLY', 'name': "O'Reilly Automotive, Inc."},
{'symbol': 'OXY', 'name': 'Occidental Petroleum Corporation'},
{'symbol': 'ODFL', 'name': 'Old Dominion Freight Line, Inc.'},
{'symbol': 'OMC', 'name': 'Omnicom Group Inc.'},
{'symbol': 'ON', 'name': 'ON Semiconductor Corporation'},
{'symbol': 'OKE', 'name': 'ONEOK, Inc.'},
{'symbol': 'ORCL', 'name': 'Oracle Corporation'},
{'symbol': 'OTIS', 'name': 'Otis Worldwide Corporation'},
{'symbol': 'PCAR', 'name': 'PACCAR Inc'},
{'symbol': 'PKG', 'name': 'Packaging Corporation of America'},
{'symbol': 'PLTR', 'name': 'Palantir Technologies Inc.'},
{'symbol': 'PANW', 'name': 'Palo Alto Networks, Inc.'},
{'symbol': 'PARA', 'name': 'Paramount Global'},
{'symbol': 'PH', 'name': 'Parker-Hannifin Corporation'},
{'symbol': 'PAYX', 'name': 'Paychex, Inc.'},
{'symbol': 'PAYC', 'name': 'Paycom Software, Inc.'},
{'symbol': 'PYPL', 'name': 'PayPal Holdings, Inc.'},
{'symbol': 'PNR', 'name': 'Pentair plc'},
{'symbol': 'PEP', 'name': 'PepsiCo, Inc.'},
{'symbol': 'PFE', 'name': 'Pfizer Inc.'},
{'symbol': 'PCG', 'name': 'PG&E Corporation'},
{'symbol': 'PM', 'name': 'Philip Morris International Inc.'},
{'symbol': 'PSX', 'name': 'Phillips 66'},
{'symbol': 'PNW', 'name': 'Pinnacle West Capital Corporation'},
{'symbol': 'PNC', 'name': 'The PNC Financial Services Group, Inc.'},
{'symbol': 'POOL', 'name': 'Pool Corporation'},
{'symbol': 'PPG', 'name': 'PPG Industries, Inc.'},
{'symbol': 'PPL', 'name': 'PPL Corporation'},
{'symbol': 'PFG', 'name': 'Principal Financial Group, Inc.'},
{'symbol': 'PG', 'name': 'The Procter & Gamble Company'},
{'symbol': 'PGR', 'name': 'The Progressive Corporation'},
{'symbol': 'PLD', 'name': 'Prologis, Inc.'},
{'symbol': 'PRU', 'name': 'Prudential Financial, Inc.'},
{'symbol': 'PEG', 'name': 'Public Service Enterprise Group Incorporated'},
{'symbol': 'PTC', 'name': 'PTC Inc.'},
{'symbol': 'PSA', 'name': 'Public Storage'},
{'symbol': 'PHM', 'name': 'PulteGroup, Inc.'},
{'symbol': 'PWR', 'name': 'Quanta Services, Inc.'},
{'symbol': 'QCOM', 'name': 'QUALCOMM Incorporated'},
{'symbol': 'DGX', 'name': 'Quest Diagnostics Incorporated'},
{'symbol': 'RL', 'name': 'Ralph Lauren Corporation'},
{'symbol': 'RJF', 'name': 'Raymond James Financial, Inc.'},
{'symbol': 'RTX', 'name': 'RTX Corporation'},
{'symbol': 'O', 'name': 'Realty Income Corporation'},
{'symbol': 'REG', 'name': 'Regency Centers Corporation'},
{'symbol': 'REGN', 'name': 'Regeneron Pharmaceuticals, Inc.'},
{'symbol': 'RF', 'name': 'Regions Financial Corporation'},
{'symbol': 'RSG', 'name': 'Republic Services, Inc.'},
{'symbol': 'RMD', 'name': 'ResMed Inc.'},
{'symbol': 'RVTY', 'name': 'Revvity, Inc.'},
{'symbol': 'ROK', 'name': 'Rockwell Automation, Inc.'},
{'symbol': 'ROL', 'name': 'Rollins, Inc.'},
{'symbol': 'ROP', 'name': 'Roper Technologies, Inc.'},
{'symbol': 'ROST', 'name': 'Ross Stores, Inc.'},
{'symbol': 'RCL', 'name': 'Royal Caribbean Cruises Ltd.'},
{'symbol': 'SPGI', 'name': 'S&P Global Inc.'},
{'symbol': 'CRM', 'name': 'Salesforce, Inc.'},
{'symbol': 'SBAC', 'name': 'SBA Communications Corporation'},
{'symbol': 'SLB', 'name': 'Schlumberger Limited'},
{'symbol': 'STX', 'name': 'Seagate Technology Holdings plc'},
{'symbol': 'SRE', 'name': 'Sempra'},
{'symbol': 'NOW', 'name': 'ServiceNow, Inc.'},
{'symbol': 'SHW', 'name': 'The Sherwin-Williams Company'},
{'symbol': 'SPG', 'name': 'Simon Property Group, Inc.'},
{'symbol': 'SWKS', 'name': 'Skyworks Solutions, Inc.'},
{'symbol': 'SJM', 'name': 'The J. M. Smucker Company'},
{'symbol': 'SNA', 'name': 'Snap-on Incorporated'},
{'symbol': 'SO', 'name': 'The Southern Company'},
{'symbol': 'LUV', 'name': 'Southwest Airlines Co.'},
{'symbol': 'SWK', 'name': 'Stanley Black & Decker, Inc.'},
{'symbol': 'SBUX', 'name': 'Starbucks Corporation'},
{'symbol': 'STT', 'name': 'State Street Corporation'},
{'symbol': 'STLD', 'name': 'Steel Dynamics, Inc.'},
{'symbol': 'STE', 'name': 'STERIS plc'},
{'symbol': 'SYK', 'name': 'Stryker Corporation'},
{'symbol': 'SMCI', 'name': 'Super Micro Computer, Inc.'},
{'symbol': 'SYF', 'name': 'Synchrony Financial'},
{'symbol': 'SNPS', 'name': 'Synopsys, Inc.'},
{'symbol': 'SYY', 'name': 'Sysco Corporation'},
{'symbol': 'TMUS', 'name': 'T-Mobile US, Inc.'},
{'symbol': 'TROW', 'name': 'T. Rowe Price Group, Inc.'},
{'symbol': 'TTWO', 'name': 'Take-Two Interactive Software, Inc.'},
{'symbol': 'TPR', 'name': 'Tapestry, Inc.'},
{'symbol': 'TRGP', 'name': 'Targa Resources Corp.'},
{'symbol': 'TGT', 'name': 'null'},
{'symbol': 'TEL', 'name': 'TE Connectivity plc'},
{'symbol': 'TDY', 'name': 'Teledyne Technologies Incorporated'},
{'symbol': 'TFX', 'name': 'Teleflex Incorporated'},
{'symbol': 'TER', 'name': 'Teradyne, Inc.'},
{'symbol': 'TSLA', 'name': 'Tesla, Inc.'},
{'symbol': 'TXN', 'name': 'Texas Instruments Incorporated'},
{'symbol': 'TPL', 'name': 'Texas Pacific Land Corporation'},
{'symbol': 'TXT', 'name': 'Textron Inc.'},
{'symbol': 'TMO', 'name': 'Thermo Fisher Scientific Inc.'},
{'symbol': 'TJX', 'name': 'The TJX Companies, Inc.'},
{'symbol': 'TSCO', 'name': 'Tractor Supply Company'},
{'symbol': 'TT', 'name': 'Trane Technologies plc'},
{'symbol': 'TDG', 'name': 'TransDigm Group Incorporated'},
{'symbol': 'TRV', 'name': 'The Travelers Companies, Inc.'},
{'symbol': 'TRMB', 'name': 'Trimble Inc.'},
{'symbol': 'TFC', 'name': 'Truist Financial Corporation'},
{'symbol': 'TYL', 'name': 'Tyler Technologies, Inc.'},
{'symbol': 'TSN', 'name': 'Tyson Foods, Inc.'},
{'symbol': 'USB', 'name': 'U.S. Bancorp'},
{'symbol': 'UBER', 'name': 'Uber Technologies, Inc.'},
{'symbol': 'UDR', 'name': 'UDR, Inc.'},
{'symbol': 'ULTA', 'name': 'Ulta Beauty, Inc.'},
{'symbol': 'UNP', 'name': 'Union Pacific Corporation'},
{'symbol': 'UAL', 'name': 'United Airlines Holdings, Inc.'},
{'symbol': 'UPS', 'name': 'United Parcel Service, Inc.'},
{'symbol': 'URI', 'name': 'United Rentals, Inc.'},
{'symbol': 'UNH', 'name': 'UnitedHealth Group Incorporated'},
{'symbol': 'UHS', 'name': 'Universal Health Services, Inc.'},
{'symbol': 'VLO', 'name': 'Valero Energy Corporation'},
{'symbol': 'VTR', 'name': 'Ventas, Inc.'},
{'symbol': 'VRSN', 'name': 'VeriSign, Inc.'},
{'symbol': 'VRSK', 'name': 'Verisk Analytics, Inc.'},
{'symbol': 'VZ', 'name': 'Verizon Communications Inc.'},
{'symbol': 'VRTX', 'name': 'Vertex Pharmaceuticals Incorporated'},
{'symbol': 'VTRS', 'name': 'Viatris Inc.'},
{'symbol': 'VICI', 'name': 'VICI Properties Inc.'},
{'symbol': 'V', 'name': 'Visa Inc.'},
{'symbol': 'VST', 'name': 'Vistra Corp.'},
{'symbol': 'VMC', 'name': 'Vulcan Materials Company'},
{'symbol': 'WRB', 'name': 'W. R. Berkley Corporation'},
{'symbol': 'GWW', 'name': 'W.W. Grainger, Inc.'},
{'symbol': 'WAB', 'name': 'Westinghouse Air Brake Technologies Corporation'},
{'symbol': 'WBA', 'name': 'Walgreens Boots Alliance, Inc.'},
{'symbol': 'WMT', 'name': 'Walmart Inc.'},
{'symbol': 'DIS', 'name': 'The Walt Disney Company'},
{'symbol': 'WBD', 'name': 'Warner Bros. Discovery, Inc.'},
{'symbol': 'WM', 'name': 'Waste Management, Inc.'},
{'symbol': 'WAT', 'name': 'Waters Corporation'},
{'symbol': 'WEC', 'name': 'WEC Energy Group, Inc.'},
{'symbol': 'WFC', 'name': 'Wells Fargo & Company'},
{'symbol': 'WELL', 'name': 'Welltower Inc.'},
{'symbol': 'WST', 'name': 'West Pharmaceutical Services, Inc.'},
{'symbol': 'WDC', 'name': 'Western Digital Corporation'},
{'symbol': 'WY', 'name': 'Weyerhaeuser Company'},
{'symbol': 'WMB', 'name': 'The Williams Companies, Inc.'},
{'symbol': 'WTW', 'name': 'Willis Towers Watson Public Limited Company'},
{'symbol': 'WDAY', 'name': 'Workday, Inc.'},
{'symbol': 'WYNN', 'name': 'Wynn Resorts, Limited'},
{'symbol': 'XEL', 'name': 'Xcel Energy Inc.'},
{'symbol': 'XYL', 'name': 'Xylem Inc.'},
{'symbol': 'YUM', 'name': 'Yum! Brands, Inc.'},
{'symbol': 'ZBRA', 'name': 'Zebra Technologies Corporation'},
{'symbol': 'ZBH', 'name': 'Zimmer Biomet Holdings, Inc.'},
{'symbol': 'ZTS', 'name': 'Zoetis Inc.'},
{'symbol': 'Sum', 'name': 'Summit Materials, Inc.'},
];
