// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPAP7G-ehJlfvBWeXlP-HIAgU411bhEG4',
    appId: '1:108936432344:web:44f4cfa07071ecd28165ad',
    messagingSenderId: '108936432344',
    projectId: 'stockmind-testing',
    authDomain: 'stockmind-testing.firebaseapp.com',
    storageBucket: 'stockmind-testing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKtwUjtDJFc4utCmQ0g6OzpZMkIpHTg1U',
    appId: '1:108936432344:android:6ff6652a01c489ad8165ad',
    messagingSenderId: '108936432344',
    projectId: 'stockmind-testing',
    storageBucket: 'stockmind-testing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7KeBBmdL1Pfc08I4u3qC_JBu50Qqpb-Y',
    appId: '1:108936432344:ios:3c14c7b44fc85db38165ad',
    messagingSenderId: '108936432344',
    projectId: 'stockmind-testing',
    storageBucket: 'stockmind-testing.firebasestorage.app',
    iosClientId: '108936432344-4dq7pn9cr5guqtn4olgenssefkq7np8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.blazemobile',
  );
}
