// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdQORXmwRMlZ0Msd2oZLQucFe4QPKGRU',
    appId: '1:371040049144:web:6fa70583418e332453e80d',
    messagingSenderId: '371040049144',
    projectId: 'stockmind-d4149',
    authDomain: 'stockmind-d4149.firebaseapp.com',
    storageBucket: 'stockmind-d4149.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUlQOkxxDaCMkJ1LGaOGRBakh14_3HEA',
    appId: '1:371040049144:android:dcc94a0540216b0153e80d',
    messagingSenderId: '371040049144',
    projectId: 'stockmind-d4149',
    storageBucket: 'stockmind-d4149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS2wugOfpUFM420n1-xXlx-ULHnjqpW4s',
    appId: '1:371040049144:ios:2f29c065013489eb53e80d',
    messagingSenderId: '371040049144',
    projectId: 'stockmind-d4149',
    storageBucket: 'stockmind-d4149.firebasestorage.app',
    androidClientId: '371040049144-0okc2lg60soh7ovd39o2k3uclh99tppf.apps.googleusercontent.com',
    iosClientId: '371040049144-si5f6dglvmolnvca2rq5s2g5npvagu3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.blazemobile',
  );
}
